"423482321":
  mode: true
  server:
    id: "1"
    name: 小钰
    version: "3.2"
    ip: 192.168.56.128
    port: 20011
    region: dev_gio
    sign: zyy
    signswitch: "false"
  Administrator:
    - "1072411694"
  uid:
    - "1072411294": "10002"
"1072411694":
  mode: false
  server:
    id: "1"
    name: 小钰
    version: "3.2"
    ip: 192.168.56.128
    port: 20011
    region: dev_gio
    sign: zyy
    signswitch: "false"
  Administrator:
    - "1072411694"
  uid:
    - "10724112694": "10002"
